### PR TITLE
Add udev rules for tegra_vde

### PR DESCRIPTION
**Pull request by kwizart**
Btw, Is there a way to use 660 instead of 0666 like others dri devices ?

ls -al /dev/dri/{card0,renderD128}
crw-rw----+ 1 root video 226,   0 24 juil. 08:26 /dev/dri/card0
crw-rw----+ 1 root video 226, 128 24 juil. 08:26 /dev/dri/renderD128

### CODE REVIEW

**Comment by digetx** [comment]
Very nice, adding an UDEV rule was on my TODO list =)

Do you mean 660 for the UDEV rule? If yes, I think 660 should be more appropriate since UDEV would change group to `video` for the device file.

We also should change automake's makefile.am / configure.ac to install the rule.

**Comment by kwizart** [comment]
> Do you mean 660 for the UDEV rule? If yes, I think 660 should be more appropriate since UDEV would change group to video for the device file.

Yep, but then it doesn't work for me. Note that i'm using a xserver that do not have setuid root.

**Comment by digetx** [comment]
I tested this UDEV rule with 660 permissions on a rootless Xorg, it work fine for me. What error do you get?

**Comment by kwizart** [comment]
When changing perm to 0660 root:video, I have permission denied when using vdpauinfo
changing to 0666 make vdpauinfo to work

**Comment by kwizart** [comment]
FYI, I have a 4.12.0 kernel from late June, maybe changes have been made on the kernel side to improve this.

(I will try to implement the udev installation rule at a later point)

**Comment by digetx** [comment]
I realized that I was testing a wrong Xorg executable and actually I can't start rootless Xorg. I'll try to fix my rootless Xorg setup and test it again.

**Comment by digetx** [comment]
I got rootless Xorg working and still VDPAU works fine with 0660.

**Comment by digetx** [comment]
@kwizart I'm merging your PR since finally I got my hands on making UDEV rule installable. Thanks!

**Pull request merged**
